### ISSUE TITLE
Add an option to allow Void Leviathan to spawn again.

### ISSUE THREAD

**Issue by TsameCorvy** [VoidLeech/VoidedEnlightenment#1]
I understand the reasons to stop it from spawning, but there definitely should be an option to allow its spawn like normal. I find encounters with them funny and even a bit eerie considering the way it just has its mouth open while slowly approaching you while lacking animations. I think it's supposed to do that, stop you from getting the new shiny gear while giving no reason to fight it at all, like the Warden. That makes me wonder if a system similar to the Warden's could be applied for the Void Leviathan sometime in the future on the original mod or your patches.

Anyways, please add that option to the config if possible, thanks!

**Comment by VoidLeech** [comment]
This config is actually already implemented in dev. I still need to do art stuff before I can release the update though, and I've had it quite busy.

**Comment by VoidLeech** [comment]
A version with this config is now publicly available.
